//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DATA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CLINICAEntities1 : DbContext
    {
        public CLINICAEntities1()
            : base("name=CLINICAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
    
        public virtual int SP_ACTUALIZAPACIENTE(Nullable<int> iD_PAC, string nOM, string aPE, Nullable<System.DateTime> fNA_PAC, string fON)
        {
            var iD_PACParameter = iD_PAC.HasValue ?
                new ObjectParameter("ID_PAC", iD_PAC) :
                new ObjectParameter("ID_PAC", typeof(int));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var aPEParameter = aPE != null ?
                new ObjectParameter("APE", aPE) :
                new ObjectParameter("APE", typeof(string));
    
            var fNA_PACParameter = fNA_PAC.HasValue ?
                new ObjectParameter("FNA_PAC", fNA_PAC) :
                new ObjectParameter("FNA_PAC", typeof(System.DateTime));
    
            var fONParameter = fON != null ?
                new ObjectParameter("FON", fON) :
                new ObjectParameter("FON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAPACIENTE", iD_PACParameter, nOMParameter, aPEParameter, fNA_PACParameter, fONParameter);
        }
    
        public virtual int SP_ELIMINAPACIENTE(Nullable<int> iD_PAC)
        {
            var iD_PACParameter = iD_PAC.HasValue ?
                new ObjectParameter("ID_PAC", iD_PAC) :
                new ObjectParameter("ID_PAC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAPACIENTE", iD_PACParameter);
        }
    
        public virtual ObjectResult<SP_LISTAPACIENTE_Result> SP_LISTAPACIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAPACIENTE_Result>("SP_LISTAPACIENTE");
        }
    
        public virtual int SP_NUEVOPACIENTE(string nOM, string aPE, Nullable<System.DateTime> fNA_PAC, string fON)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var aPEParameter = aPE != null ?
                new ObjectParameter("APE", aPE) :
                new ObjectParameter("APE", typeof(string));
    
            var fNA_PACParameter = fNA_PAC.HasValue ?
                new ObjectParameter("FNA_PAC", fNA_PAC) :
                new ObjectParameter("FNA_PAC", typeof(System.DateTime));
    
            var fONParameter = fON != null ?
                new ObjectParameter("FON", fON) :
                new ObjectParameter("FON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NUEVOPACIENTE", nOMParameter, aPEParameter, fNA_PACParameter, fONParameter);
        }
    }
}
