//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.DATA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public int IDE_PAC { get; set; }
        public string NOM_PAC { get; set; }
        public string APE_PAC { get; set; }
        public System.DateTime FNA_PAC { get; set; }
        public string FON_PAC { get; set; }
    }
}
